Repository ember-codemods/ember-angle-brackets-codemod, pull requests merged in 2019-10, with the labels that each got.

#47 Add whitespace control test
  transforms/angle-brackets/test.js
Labels: internal

#144 Fix inline link-to with subexpression caption crash
  transforms/angle-brackets/test.js
  transforms/angle-brackets/transform.js
Labels: bug

#149 Add test case for splattributes
  transforms/angle-brackets/test.js
Labels: internal

#152 fix migrating away from arguments to attributes for non-builtins
  transforms/angle-brackets/test.js
  transforms/angle-brackets/transform.js
Labels: enhancement

#163 Add test case for nested else if
  transforms/angle-brackets/test.js
Labels: internal

#168 Skip block component conversion if the component has an `inverse` block
  transforms/angle-brackets/test.js
  transforms/angle-brackets/transform.js
Labels: bug

#155 Add a Logger
  lib/logger.js
  package.json
  transforms/angle-brackets/transform.js
  yarn.lock
Labels: enhancement

#181 Add support for templates containing `~` (whitespace control)
  transforms/angle-brackets/test.js
  transforms/angle-brackets/transform.js
Labels: enhancement

#182 fix hyphen usage
  transforms/angle-brackets/test.js
  transforms/angle-brackets/transform.js
Labels: bug
