Repository ember-codemods/ember-angle-brackets-codemod, pull requests merged in 2019-09, with the labels that each got.

#128 Remove `husky` and `lint-staged` dev dependencies
  package-lock.json
  package.json
Labels: internal

#130 package.json: Sort contents according to documentation
  package.json
Labels: internal

#131 package.json: Remove broken `main` field
  package.json
Labels: bug

#132 Replace `ember-addon` keyword with `ember-codemod`
  package.json
Labels: internal

#133 Update dependencies
  package-lock.json
  package.json
Labels: internal

#136 Cleanup file structure
  package.json
  transforms/-preset.js
  transforms/angle-brackets/index.js
  transforms/angle-brackets/transform.js
Labels: internal

#137 Update list of common helpers
  transforms/angle-brackets/transform.js
Labels: enhancement

#134 Remove obsolete ASTExplorer files
  astexplorer.json
  source.handlebars
Labels: internal

#135 ESLint: Fix test path pattern
  .eslintrc.js
Labels: internal

#139 CI: Run ESLint
  .travis.yml
  bin/cli.js
  package.json
Labels: internal

#140 bin/cli: Set correct file extension
  bin/cli.js
Labels: bug

#141 Adjust `tilde` test fixture
  transforms/angle-brackets/__snapshots__/test.js.snap
  transforms/angle-brackets/test.js
Labels: internal

#142 tests: Use inline snapshots
  package-lock.json
  package.json
  transforms/angle-brackets/__snapshots__/test.js.snap
  transforms/angle-brackets/test.js
Labels: internal

#97 Use `ember-template-recast` to preserve existing template formatting as much as possible
  package-lock.json
  package.json
  transforms/angle-brackets/test.js
  transforms/angle-brackets/transform.js
Labels: enhancement

#143 Use yarn instead of npm internally
  .travis.yml
  package-lock.json
  yarn.lock
Labels: internal
